<?php
$group_575a597a5deb4_field_data = array(
	'key'                   => 'group_575a597a5deb4',
	'title'                 => 'Portfolio Details',
	'fields'                => array(
		array(
			'key'               => 'field_575a5c2ad0db9',
			'label'             => 'General Details',
			'name'              => '',
			'type'              => 'tab',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => 0,
			'wrapper'           => array(
				'width' => '',
				'class' => 'acf_field_name- acf_field_name-',
				'id'    => '',
			),
			'placement'         => 'top',
			'endpoint'          => 0,
		),
		array(
			'key'               => 'field_575a5abfa2ff8',
			'label'             => 'Client Name',
			'name'              => 'client_name',
			'type'              => 'text',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => 0,
			'wrapper'           => array(
				'width' => '',
				'class' => 'acf_field_name-client_name acf_field_name-client_name',
				'id'    => '',
			),
			'default_value'     => '',
			'placeholder'       => '',
			'prepend'           => '',
			'append'            => '',
			'maxlength'         => '',
			'readonly'          => 0,
			'disabled'          => 0,
		),
		array(
			'key'               => 'field_575a5b4463109',
			'label'             => 'Project Url',
			'name'              => 'project_url',
			'type'              => 'url',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => 0,
			'wrapper'           => array(
				'width' => '',
				'class' => 'acf_field_name-project_url acf_field_name-project_url',
				'id'    => '',
			),
			'default_value'     => '',
			'placeholder'       => '',
		),
		array(
			'key'               => 'field_575a5996a4b48',
			'label'             => 'Release Date',
			'name'              => 'release_date',
			'type'              => 'date_picker',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => 0,
			'wrapper'           => array(
				'width' => '',
				'class' => 'acf_field_name-release acf_field_name-release',
				'id'    => '',
			),
			'display_format'    => 'd/m/Y',
			'return_format'     => 'Ymd',
			'first_day'         => 1,
		),
		array(
			'key'               => 'field_57cd4cc7c4469',
			'label'             => 'Related Portfolio',
			'name'              => 'related_portfolio',
			'type'              => 'true_false',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => 0,
			'wrapper'           => array(
				'width' => '',
				'class' => 'acf_field_name-related_portfolio_posts acf_field_name-related_portfolio_posts',
				'id'    => '',
			),
			'message'           => 'Check this field to show related portfolio.',
			'default_value'     => 1,
			'ui'                => 0,
			'ui_on_text'        => '',
			'ui_off_text'       => '',
		),
		array(
			'key'               => 'field_575a5c67a77c8',
			'label'             => 'Portfolio Images',
			'name'              => '',
			'type'              => 'tab',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => 0,
			'wrapper'           => array(
				'width' => '',
				'class' => 'acf_field_name-portfolio_image_ acf_field_name-portfolio_image_',
				'id'    => '',
			),
			'placement'         => 'top',
			'endpoint'          => 0,
		),
		array(
			'key'               => 'field_575a5c34d0dba',
			'label'             => 'Portfolio Images',
			'name'              => 'portfolio_images',
			'type'              => 'gallery',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => 0,
			'wrapper'           => array(
				'width' => '',
				'class' => 'acf_field_name-portfolio_images acf_field_name-portfolio_images',
				'id'    => '',
			),
			'min'               => '',
			'max'               => '',
			'preview_size'      => 'thumbnail',
			'insert'            => 'append',
			'library'           => 'all',
			'min_width'         => '',
			'min_height'        => '',
			'min_size'          => '',
			'max_width'         => '',
			'max_height'        => '',
			'max_size'          => '',
			'mime_types'        => 'jpg, png, jpeg',
		),
	),
	'location'              => array(
		array(
			array(
				'param'    => 'post_type',
				'operator' => '==',
				'value'    => 'portfolio',
			),
		),
	),
	'menu_order'            => 0,
	'position'              => 'normal',
	'style'                 => 'default',
	'label_placement'       => 'top',
	'instruction_placement' => 'field',
	'hide_on_screen'        => '',
	'active'                => 1,
	'description'           => '',
	'modified'              => 1487676192,
);
//acf_add_local_field_group( apply_filters( 'portfolio_details_group_575a597a5deb4', $group_575a597a5deb4_field_data ) );

