<?php
$group_57503acdbcf89_field_data = array(
	'key'                   => 'group_57503acdbcf89',
	'title'                 => 'Post Format - Gallery',
	'fields'                => array(
		array(
			'key'               => 'field_57503d1deb752',
			'label'             => 'Gallery Type',
			'name'              => 'gallery_type',
			'type'              => 'radio',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => 0,
			'wrapper'           => array(
				'width' => '',
				'class' => '',
				'id'    => '',
			),
			'choices'           => array(
				'slider' => 'Slider',
				'grid'   => 'Grid',
			),
			'allow_null'        => 0,
			'other_choice'      => 0,
			'save_other_choice' => 0,
			'default_value'     => 'slider',
			'layout'            => 'horizontal',
			'return_format'     => 'value',
		),
		array(
			'key'               => 'field_5755486b0ee98',
			'label'             => '',
			'name'              => '',
			'type'              => 'message',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => array(
				array(
					array(
						'field'    => 'field_57503d1deb752',
						'operator' => '==',
						'value'    => 'grid',
					),
				),
			),
			'wrapper'           => array(
				'width' => '',
				'class' => '',
				'id'    => '',
			),
			'message'           => '<span style="color:#f00;">Add images in count 2 or 4.</span>',
			'new_lines'         => 'wpautop',
			'esc_html'          => 0,
		),
		array(
			'key'               => 'field_57512e726c0c1',
			'label'             => 'Gallery Images',
			'name'              => 'gallery_images',
			'type'              => 'repeater',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => 0,
			'wrapper'           => array(
				'width' => '',
				'class' => '',
				'id'    => '',
			),
			'collapsed'         => 'field_57512eb96c0c2',
			'min'               => 0,
			'max'               => 0,
			'layout'            => 'table',
			'button_label'      => 'Add Image',
			'sub_fields'        => array(
				array(
					'key'               => 'field_57512eb96c0c2',
					'label'             => 'Image',
					'name'              => 'image',
					'type'              => 'image',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'return_format'     => 'array',
					'preview_size'      => 'thumbnail',
					'library'           => 'all',
					'min_width'         => '',
					'min_height'        => '',
					'min_size'          => '',
					'max_width'         => '',
					'max_height'        => '',
					'max_size'          => '',
					'mime_types'        => '',
				),
			),
		),
	),
	'location'              => array(
		array(
			array(
				'param'    => 'post_type',
				'operator' => '==',
				'value'    => 'post',
			),
			array(
				'param'    => 'post_format',
				'operator' => '==',
				'value'    => 'gallery',
			),
		),
	),
	'menu_order'            => 0,
	'position'              => 'normal',
	'style'                 => 'default',
	'label_placement'       => 'top',
	'instruction_placement' => 'field',
	'hide_on_screen'        => '',
	'active'                => 1,
	'description'           => '',
	'modified'              => 1487679170,
);
acf_add_local_field_group( apply_filters( 'post_format_gallery_group_57503acdbcf89', $group_57503acdbcf89_field_data ) );

