<?php
$group_5755547943bdc_field_data = array(
	'key'                   => 'group_5755547943bdc',
	'title'                 => 'Post Format - Video',
	'fields'                => array(
		array(
			'key'               => 'field_5755548e99883',
			'label'             => 'Video Type',
			'name'              => 'video_type',
			'type'              => 'radio',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => 0,
			'wrapper'           => array(
				'width' => '',
				'class' => '',
				'id'    => '',
			),
			'choices'           => array(
				'html5'   => 'HTML5',
				'youtube' => 'YouTube',
				'vimeo'   => 'Vimeo',
			),
			'allow_null'        => 0,
			'other_choice'      => 0,
			'save_other_choice' => 0,
			'default_value'     => 'youtube',
			'layout'            => 'horizontal',
			'return_format'     => 'value',
		),
		array(
			'key'               => 'field_575554fb99884',
			'label'             => 'YouTube Video',
			'name'              => 'post_format_video_youtube',
			'type'              => 'oembed',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => array(
				array(
					array(
						'field'    => 'field_5755548e99883',
						'operator' => '==',
						'value'    => 'youtube',
					),
				),
			),
			'wrapper'           => array(
				'width' => '',
				'class' => '',
				'id'    => '',
			),
			'width'             => '',
			'height'            => '',
		),
		array(
			'key'               => 'field_5755559f99885',
			'label'             => 'Vimeo Video',
			'name'              => 'post_format_video_vimeo',
			'type'              => 'oembed',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => array(
				array(
					array(
						'field'    => 'field_5755548e99883',
						'operator' => '==',
						'value'    => 'vimeo',
					),
				),
			),
			'wrapper'           => array(
				'width' => '',
				'class' => '',
				'id'    => '',
			),
			'width'             => '',
			'height'            => '',
		),
		array(
			'key'               => 'field_575555af99886',
			'label'             => 'HTML5 Video',
			'name'              => 'post_format_video_html5',
			'type'              => 'repeater',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => array(
				array(
					array(
						'field'    => 'field_5755548e99883',
						'operator' => '==',
						'value'    => 'html5',
					),
				),
			),
			'wrapper'           => array(
				'width' => '',
				'class' => '',
				'id'    => '',
			),
			'collapsed'         => '',
			'min'               => 1,
			'max'               => 1,
			'layout'            => 'row',
			'button_label'      => 'Add Row',
			'sub_fields'        => array(
				array(
					'key'               => 'field_5755575499887',
					'label'             => 'MP4',
					'name'              => 'mp4',
					'type'              => 'file',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'return_format'     => 'array',
					'library'           => 'all',
					'min_size'          => '',
					'max_size'          => '',
					'mime_types'        => 'mp4',
				),
				array(
					'key'               => 'field_575557b099888',
					'label'             => 'WebM',
					'name'              => 'webm',
					'type'              => 'file',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'return_format'     => 'array',
					'library'           => 'all',
					'min_size'          => '',
					'max_size'          => '',
					'mime_types'        => 'webm',
				),
				array(
					'key'               => 'field_575557ce99889',
					'label'             => 'OGV',
					'name'              => 'ogv',
					'type'              => 'file',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'return_format'     => 'array',
					'library'           => 'all',
					'min_size'          => '',
					'max_size'          => '',
					'mime_types'        => 'ogv',
				),
				array(
					'key'               => 'field_575557dd9988a',
					'label'             => 'Cover',
					'name'              => 'cover',
					'type'              => 'image',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'return_format'     => 'array',
					'preview_size'      => 'thumbnail',
					'library'           => 'all',
					'min_width'         => '',
					'min_height'        => '',
					'min_size'          => '',
					'max_width'         => '',
					'max_height'        => '',
					'max_size'          => '',
					'mime_types'        => '',
				),
			),
		),
	),
	'location'              => array(
		array(
			array(
				'param'    => 'post_type',
				'operator' => '==',
				'value'    => 'post',
			),
			array(
				'param'    => 'post_format',
				'operator' => '==',
				'value'    => 'video',
			),
		),
	),
	'menu_order'            => 0,
	'position'              => 'normal',
	'style'                 => 'default',
	'label_placement'       => 'top',
	'instruction_placement' => 'field',
	'hide_on_screen'        => '',
	'active'                => 1,
	'description'           => '',
	'modified'              => 1487679234,
);
acf_add_local_field_group( apply_filters( 'post_format_video_group_5755547943bdc', $group_5755547943bdc_field_data ) );

