<?php
$group_57a46e1723537_field_data = array(
	'key'                   => 'group_57a46e1723537',
	'title'                 => 'Testimonials',
	'fields'                => array(
		array(
			'key'               => 'field_57a46e3928abf',
			'label'             => 'Content',
			'name'              => 'content',
			'type'              => 'textarea',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => 0,
			'wrapper'           => array(
				'width' => '',
				'class' => '',
				'id'    => '',
			),
			'default_value'     => '',
			'placeholder'       => '',
			'maxlength'         => '',
			'rows'              => '',
			'new_lines'         => 'wpautop',
		),
		array(
			'key'               => 'field_58ae91fca1415',
			'label'             => 'Author',
			'name'              => 'author',
			'type'              => 'text',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => 0,
			'wrapper'           => array(
				'width' => '',
				'class' => '',
				'id'    => '',
			),
			'default_value'     => '',
			'placeholder'       => '',
			'prepend'           => '',
			'append'            => '',
			'maxlength'         => '',
		),
		array(
			'key'               => 'field_57a46e2a28abe',
			'label'             => 'Designation',
			'name'              => 'designation',
			'type'              => 'text',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => 0,
			'wrapper'           => array(
				'width' => '',
				'class' => '',
				'id'    => '',
			),
			'default_value'     => '',
			'placeholder'       => '',
			'prepend'           => '',
			'append'            => '',
			'maxlength'         => '',
		),
	),
	'location'              => array(
		array(
			array(
				'param'    => 'post_type',
				'operator' => '==',
				'value'    => 'testimonials',
			),
		),
	),
	'menu_order'            => 0,
	'position'              => 'normal',
	'style'                 => 'seamless',
	'label_placement'       => 'top',
	'instruction_placement' => 'field',
	'hide_on_screen'        => array(
		0  => 'permalink',
		1  => 'the_content',
		2  => 'excerpt',
		3  => 'custom_fields',
		4  => 'discussion',
		5  => 'comments',
		6  => 'revisions',
		7  => 'slug',
		8  => 'author',
		9  => 'format',
		10 => 'page_attributes',
		11 => 'categories',
		12 => 'tags',
		13 => 'send-trackbacks',
	),
	'active'                => 1,
	'description'           => '',
	'modified'              => 1487835664,
);
acf_add_local_field_group( apply_filters( 'testimonials_group_57a46e1723537', $group_57a46e1723537_field_data ) );

