<?php
//About Banner
return array(
	'name'             => esc_html__( 'Action Box Image Color Overlay', 'ciyashop' ),
	'template_category'=> esc_html__( 'Action Box', 'ciyashop' ),
	'disabled'         => true,                                        // Disable it to not show in the default tab
	'content'          => <<<CONTENT
[vc_row full_width="stretch_row" pgscore_enable_responsive_settings="true" pgscore_enable_overlay="true" enable_first_overlay="true" first_overlay_opacity="80" first_background_color="#2985e1" enable_parallax="true" el_id="1514971744862-9bd15f84-cb6d" css=".vc_custom_1545040361139{margin-top: 80px !important;margin-bottom: 80px !important;padding-top: 70px !important;padding-bottom: 60px !important;background-image: url(https://ciyashop.potenzaglobalsolutions.com/medical/wp-content/uploads/sites/55/2018/01/ed5be-01.jpg?id=11500) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}" element_css_md=".vc_custom_1545040361144{margin-top: 60px !important;margin-bottom: 60px !important;padding-top: 60px !important;}" element_css_sm=".vc_custom_1545040361148{margin-top: 50px !important;margin-bottom: 50px !important;padding-top: 50px !important;padding-bottom: 50px !important;}" element_css_xs=".vc_custom_1545040361150{margin-top: 40px !important;margin-bottom: 40px !important;padding-top: 40px !important;padding-bottom: 40px !important;}" pgscore_overlay_color="rgba(41,133,225,0.8)"][vc_column css=".vc_custom_1514899656779{padding-top: 0px !important;}"][vc_custom_heading text="Free Appointment Booking" font_container="tag:h2|text_align:center|color:%23ffffff" use_theme_fonts="yes" font_weight="800" css=".vc_custom_1514965963570{margin-bottom: 20px !important;}"][vc_custom_heading text="Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, scrambled it to make a type specimen book." font_container="tag:h6|text_align:center|color:%23ffffff|line_height:34px" use_theme_fonts="yes" css=".vc_custom_1514966304979{margin-bottom: 20px !important;padding-right: 15% !important;padding-left: 15% !important;}"][vc_row_inner][vc_column_inner el_class="text-center" css=".vc_custom_1514968168217{padding-top: 0px !important;}"][pgscore_button button_type="border" button_border_color="#ffffff" button_border_hover_color="#ffffff" button_border="rounded" button_size="large" button_other_type_text_color="#ffffff" button_other_type_text_hover_color="#ffffff" button_inline_style="center" button_title="MAKE AN APPOINTMENT" button_link="url:%23|title:MAKE%20AN%20APPOINTMENT||"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]
CONTENT
);